socksAddress: "localhost"
socksPort: 7890
upstream:
  proxyProviders:
    - url: "http://colaleo.top/api/v1/client/subscribe?token=6c37ab3b94f68f636b1dbd25c81bd7d4&flag=clash"
      path: proxy/老八机场.yaml

  ruleProviders:
    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
      path: ruleset/reject.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
      path: ruleset/icloud.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
      path: ruleset/apple.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
      path: ruleset/google.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
      path: ruleset/proxy.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
      path: ruleset/direct.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
      path: ruleset/private.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
      path: ruleset/gfw.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt"
      path: ruleset/greatfire.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
      path: ruleset/tld-not-cn.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
      path: ruleset/telegramcidr.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
      path: ruleset/cncidr.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
      path: ruleset/lancidr.yaml

    - url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
      path: ruleset/applications.yaml

  mmdbProviders:
    - url: "https://github.com/alecthw/mmdb_china_ip_list/releases/latest/download/Country.mmdb"
      path: Country.mmdb
